[[redirects]]
  to = "/api/plates/dc635c56-8a54-47a8-9fad-ff1e72183540.json"
  from = "/api/plates/cur.json"
  status = 200

[[redirects]]
  from = "/"
  to = "/validate.html"
  status = 302

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
